### ISSUE TITLE
Users are not able to sign in with their gmail account 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#103]
Risk: High
Priority: High
Hours: 6 hours
This is a project related issue : Occuring in all branches

**Comment by Gabbell** [comment]
This bug was fixed. I unknowingly deleted the clientId of our project on the Google Dev Console and the sign in process was complaining that the OAuth client had been deleted. After creating a new one, we had to change it from the old credentials to the new ones (clientId AND client secret) in the Firebase Web SDK.

**Comment by samratdebroy** [comment]
Hours Spent: 2 hours

**Comment by Gabbell** [comment]
Hours: 2
