### ISSUE TITLE
Display a module with an input text-box allowing the user to type an email

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#121]
Parent Issue: #106 
Hours: 2 hours

**Comment by samratdebroy** [comment]
These text boxes should appear only if the current user's email matches with the email of the professor for one of the course sections in his/her course array. Note that there can be multiple boxes for a single user.

Say our SOEN professor logs into the website with his verified email: He would see a text box appear for each of the sections he teaches that are present in his course array .  Maybe instead of having multiple boxes, we could have a single box with a dropdown in the corner that lets the professor choose for which course section he/she wants to add privileged users, but i'll leave that to the Front-End team to figure out what is best aesthetically.

**Comment by j-suguma** [comment]
I did some research and found a way to implement the add TA email, however after speaking with you guys, you implemented the email list/ professor logic differently so now ill change it to the way the back end team wants.
**Here are some pictures of how it looks now**
![image](https://cloud.githubusercontent.com/assets/25251601/24567975/fa67ea86-162d-11e7-8075-84472536e0f1.png)
![image](https://cloud.githubusercontent.com/assets/25251601/24567983/041708c8-162e-11e7-8683-7d7c1eba65a9.png)

Hours worked: 5hours

**Comment by j-suguma** [comment]
@samratdebroy  is this kind of what you wanted? Tell me any changes you want me to make
![image](https://cloud.githubusercontent.com/assets/25251601/24579402/d75b72ca-16c2-11e7-84fb-379080b3d338.png)

**Comment by samratdebroy** [comment]
Yes this is perfect! That's exactly what the backend team was thinking about.

**Comment by j-suguma** [comment]
Alright then ill go ahead and commit it to our Frontend branch soon

**Comment by svelupillai** [comment]
hours: 0.5

**Comment by jameelbrochu** [comment]
Time: 1 hour
