### ISSUE TITLE
If user was logged in with gmail account and then connects with a different account, then user is still able to export the schedule from previous gmail account

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#125]
Hours: 5 hours

**Comment by Gabbell** [comment]
Note that after this fix, the user is indeed signed out BUT if the user decides to reclick on export to calendar, the GAPI will use the previously generated cookie to immediately sign back in even if the user is not currently connected with a Gmail account. This happens because we're using localhost. (http://stackoverflow.com/questions/22086301/gapi-auth-signout-not-working-im-lost).

**Comment by mukulikadey** [comment]
This issue can be closed. It passed the requirements and all the necessary tests.

**Comment by Gabbell** [comment]
Hours: 3
