### ISSUE TITLE
Restructure the .csv file so that it can be converted to JSON in such a way as to fit our Firebase data structure.

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#64]
After concerting the .csv into JSON, we need to add the "Users" data from Firebase into the new JSON and then overwrite the entire Firebase database with the updated JSON file. This will result in the removal of the existing "courses" data tree since it will be overwritten by the data from IITS' .csv file.

Hours: 2 Hours

**Comment by samratdebroy** [comment]
At the root, there will be three nodes (course, sections and users)

*course* - This contains the full list of courses we got from IITS' .csv file where each   subsection is its own object with a key of the format Subject (e.g. SOEN) + Catalog (e.g. 341) + section (S-SX) + pat number (a number that is 1 when we have a tutorial or lecture, otherwise represents the lab number (e.g 5 for the fifth lab in that section))
It's important to note that I DID NOT add the empty "subscribers" or "timetable" fields since we concluded on last Friday's meeting that this would add unnecessary logic (with no added benefit) and that no one else other than ourselves would even look at the Firebase database (so they won't question why some courses have subscribers while others don't )

*users* - This is the same old *users* node that we had in the last structure of the database with the list of courses that a user is subscribed too. Nothing has been changed in this field.

**Comment by samratdebroy** [comment]
It was necessary to edit some of the fields provided by IITS such as the "room #" because firebase does not accept having certain characters such as '[', ']', '/', '$' and '#'. Also, the excel sheet had to be heavily modified in order to acquire the "sections" data node in the JSON format. This required using many Excel formulas to make.

**Comment by samratdebroy** [comment]
The total task took more time than expected due to the fact that the "sections" data node has been added to the database. In order to get that data, we spent much more time on Excel than expected.

**Comment by samratdebroy** [comment]
The total task took more time than expected due to the fact that the "sections" data node has been added to the database. In order to get that data, we spent much more time on Excel than expected.

The new database is active on Firebase and ready to be used by the code.

**Comment by samratdebroy** [comment]
The total task took more time than expected due to the fact that the "sections" data node has been added to the database. In order to get that data, we spent much more time on Excel than expected.

The new database is active on Firebase and ready to be used by the code.

Total Hours spent : 4 hours
