### ISSUE TITLE
As a TA/Prof user, I should be able to modify the course descriptions 

### ISSUE THREAD

**Issue by coreylevine** [mukulikadey/SOEN341-Group1#65]
Points: 8  
Risk: High
Priority: Low

- [x] Create a secondary authentication level @samratdebroy 
Hours: 4 hours 
- [x] When the user clicks on an event/class on schedule, there should be a drop down that allows you to add description (Front-end). @j-suguma @jameelbrochu @mukulikadey
Hours: 5 hours 
- [x] Add a Redux state for permission levels @samratdebroy 
Hours: 3 hours 
- [x] If a user has a higher authorization level (TA or prof) for a given class, then an edit button should appear for them to be able to modify course descriptions @samratdebroy 
Hours: 5 hours
- [x] Backend & Frontend Testing @coreylevine @rekandiah 
Hours: 6 hours 

Acceptance Criteria: When a user clicks on an event on their schedule, they will see the course details including (Type of class, section, teacher, classroom, and description). Users with higher authorization(TA/Prof) will be able to modify the course descriptions.

**Comment by samratdebroy** [comment]
Below I have a gif that was taken right after subtask #98 was closed. It shows how a user white-listed for a given course can edit the description and push the changes to Firebase. At that point, all users will see the updated class description.


![editdescription_fixed](https://cloud.githubusercontent.com/assets/10346242/24218549/14780cfa-0f1a-11e7-9b77-2b20ea5f1a14.gif)

**Comment by samratdebroy** [comment]
In the gif below it can be seen that the textfield to edit the description **ONLY** appears for users whose email is in the course sections "whitelist".  Hence, in this gif I can only edit the description of the ENGR371-T section because I have priviledged rights to it, but when I click on SOEN341-S classes, I can't edit anything because I am not white-listed for that course section.  

![editdescription_finalized](https://cloud.githubusercontent.com/assets/10346242/24218680/879ea036-0f1a-11e7-887b-68086c16fb59.gif)

**Comment by mukulikadey** [comment]
This issue can be closed. When the user clicks on the schedule's events, they can see the course details. Users with higher authorizations(TA/Prof) can edit the description of that class.
