### ISSUE TITLE
As a user, I should be able to remove courses 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#81]
Points: 5  
Risk: Medium 
Priority: High

- [x] When you hover over a course, there will be an 'X' button to remove course @svelupillai 
Hours: 1 hour
- [x] Remove course from user's course array and rearrange course array @svelupillai 
Hours: 5 hours
- [x] Remove course from user's schedule event array @svelupillai 
Hours: 5 hours 
- [x] Remove subscriber from the course node @svelupillai 
Hours: 4 hours 
- [x] Switching sections should remove the subscriber from the overwritten section and add one to the new section. @samratdebroy 
Hours: 2 hours
- [x] Perform frontend/backend testing @coreylevine @rekandiah 
Hours: 4 hours

Acceptance criteria: On the home page, when the user hovers over their courses, they will see an "X" button option, allowing them to remove the course. After clicking on the button, the course will be removed from the user's course list on the home page and from their schedule on the schedule page as well.

**Comment by rekandiah** [comment]
I was testing the remove a course feature and I have suggestion...I think when the user clicks the delete a button there should be warning or alert pop up that asks the user if they want to confirm their deletion. Currently I feel like it's too abrupt. I think this would be a front end issue. What do you guys think? @j-suguma  @jameelbrochu  @mukulikadey

**Comment by samratdebroy** [comment]
Definitely agree, it's not very safe the way it is right now. Maybe we could add this next Sprint when we add the section names in the course list (if we do that). I don't think it's very high priority right now though, so we don't need to worry about it right now given how easy it is to just re-add the course you delete.

**Comment by rekandiah** [comment]
The following test case was executed manually since it could not be automated with the selenium ide.
**Given** that I am on CUSE website
**And** I have a list of courses on my homepage
**When** I delete a course
**And** I navigate to schedule page
**Then** deleted course will be removed from calendar

Before: 
<img width="616" alt="before1" src="https://cloud.githubusercontent.com/assets/15826622/24181713/3952a062-0e93-11e7-8719-56495c4321a1.png">
<img width="615" alt="before2" src="https://cloud.githubusercontent.com/assets/15826622/24181717/40376336-0e93-11e7-9869-d3d76158a341.png">

After:
<img width="616" alt="after1" src="https://cloud.githubusercontent.com/assets/15826622/24181726/48882368-0e93-11e7-8ce3-c8a41171d0b7.png">
<img width="618" alt="after2" src="https://cloud.githubusercontent.com/assets/15826622/24181731/4d474d52-0e93-11e7-9445-f4d8e163a61e.png">

**Comment by mukulikadey** [comment]
This user story can be closed. It has successfully checked off all sub-tasks, and all tests/checks were passed as well. The user can successfully remove a course from their course list and schedule.
