### ISSUE TITLE
Create a secondary authentication level

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#96]
Hours: 4 
Parent Issue: #65

**Comment by samratdebroy** [comment]
The secondary "authentication level" was simulated using Firebase Security Rules which were written directly on the Firebase console (thus there are no commits associated to this issue because the source code was not affected by these changes, only the database). The new rules stipulate that only users' whose emails are found under the section's "Whitelist" node can edit individual class "descriptions" and that the "Whitelist" node itself can only be written to by a user whose email matches with that of the professor of the course (hence only the Professor can edit this field using the proper registered email address).

**Comment by samratdebroy** [comment]
4 hours
